### ISSUE TITLE
newer version

### ISSUE THREAD

**Issue by beetlepimp0001** [idkwuu/AppleMusicWebView2#1]
needs to be made for 11.6 big sur update!

**Comment by idkwuu** [comment]
what do you mean by making it for the 11.16 update?

if you mean lossless/dolby atmos, it isn't possible because that's on Apple's side (they have to update the webapp to support them)

**Comment by beetlepimp0001** [comment]
I am getting an error that says "Check with the developer to make sure AppleMusicRPC works with this version of macOS". I have reinstalled the application and it still doesn't work. Is this application made for Apple devices?

**Comment by idkwuu** [comment]
It is not: this application was made only for Windows
